//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Kompressors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions_Parts
    {
        public int id_aParts { get; set; }
        public bool type_aParts { get; set; }
        public Nullable<int> part_aParts { get; set; }
        public string person_aParts { get; set; }
        public System.DateTime date_aParts { get; set; }
        public decimal col_aParts { get; set; }
        public decimal price_aParts { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
