//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Kompressors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions_Equipment
    {
        public int id_aEquipment { get; set; }
        public bool type_aEquipment { get; set; }
        public Nullable<int> equipment_aEquipment { get; set; }
        public string person_aEquipment { get; set; }
        public System.DateTime date_aEquipment { get; set; }
        public decimal col_aEquipment { get; set; }
        public decimal price_aEquipment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
