//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Kompressors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Actions_Equipment = new HashSet<Actions_Equipment>();
            this.Attributes_Values = new HashSet<Attributes_Values>();
            this.Parts = new HashSet<Part>();
        }
    
        public int id_equipment { get; set; }
        public string code_equipment { get; set; }
        public string name_equipment { get; set; }
        public string description_equipment { get; set; }
        public Nullable<int> fabricator_equipment { get; set; }
        public Nullable<int> category_equipment { get; set; }
        public decimal col_equipment { get; set; }
        public decimal price_equipment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actions_Equipment> Actions_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attributes_Values> Attributes_Values { get; set; }
        public virtual Сategories Сategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
        public virtual Fabricator Fabricator { get; set; }
    }
}
