//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_Kompressors
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Actions_Equipment> Actions_Equipment { get; set; }
        public virtual DbSet<Actions_Parts> Actions_Parts { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<Attributes_Values> Attributes_Values { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Fabricator> Fabricators { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Сategories> Сategories { get; set; }
    }
}
